## learn about numpy

In [4]:
import numpy as np

Creating array from list

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:", arr_2d)

Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]


### array vs list

In [8]:
list1 = [1, 2, 3, 4, 5]
print("List:", list1*2)

arr = np.array([1, 2, 3, 4, 5])
print("Array multiplied by 2:", arr*2)

List: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array multiplied by 2: [ 2  4  6  8 10]


In [11]:
import time
start_time = time.time()
list_comp = [i*2 for i in range(1000000)]
print("List comprehension time: %s seconds" % (time.time() - start_time))

start_time = time.time()
arr = np.arange(1000000) * 2
print("NumPy array operation time: %s seconds" % (time.time() - start_time))

List comprehension time: 0.09483790397644043 seconds
NumPy array operation time: 0.004240274429321289 seconds


### creating array from scratch 

In [16]:
zeros = np.zeros((3, 4))
print("Zeros Array:\n", zeros)

ones = np.ones((2, 5))
print("Ones Array:\n", ones)

full = np.full((3, 3), 7)
print("Full Array:\n", full)

randome = np.random.random((2, 2))
print("Random Array:\n", randome)

seq = np.arange(10, 21, 2)
print("Sequence Array:", seq)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random Array:
 [[0.81229215 0.61292517]
 [0.55532036 0.97196536]]
Sequence Array: [10 12 14 16 18 20]


### Vector ,Matrix,and tensor

In [20]:
vector = np.array([1, 2, 3, 4, 5])
print("Original Vector:", vector)

matrrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Matrix:\n", matrrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Original Tensor:\n", tensor)

Original Vector: [1 2 3 4 5]
Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Original Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9 ]])
print("Shape of array:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("size ", arr.size)


Shape of array: (3, 3)
Number of dimensions: 2
size  9


### Array Reshaping

In [25]:
arr = np.arange(12)
print("Original Array:", arr)
reshaped_arr = arr.reshape((3, 4))
print("Reshaped Array (3x4):\n", reshaped_arr)

flattened_arr = reshaped_arr.flatten()
print("Flattened Array:", flattened_arr)

# ravel array  returns  original array  instead of copy
raveled_arr = reshaped_arr.ravel()
print("Raveled Array:", raveled_arr)

# Transpose
transposed_arr = reshaped_arr.T
print("Transposed Array:\n", transposed_arr)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
