## learn about numpy

In [4]:
import numpy as np

Creating array from list

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:", arr_2d)

Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]


### array vs list

In [8]:
list1 = [1, 2, 3, 4, 5]
print("List:", list1*2)

arr = np.array([1, 2, 3, 4, 5])
print("Array multiplied by 2:", arr*2)

List: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array multiplied by 2: [ 2  4  6  8 10]


In [11]:
import time
start_time = time.time()
list_comp = [i*2 for i in range(1000000)]
print("List comprehension time: %s seconds" % (time.time() - start_time))

start_time = time.time()
arr = np.arange(1000000) * 2
print("NumPy array operation time: %s seconds" % (time.time() - start_time))

List comprehension time: 0.09483790397644043 seconds
NumPy array operation time: 0.004240274429321289 seconds


### creating array from scratch 

In [16]:
zeros = np.zeros((3, 4))
print("Zeros Array:\n", zeros)

ones = np.ones((2, 5))
print("Ones Array:\n", ones)

full = np.full((3, 3), 7)
print("Full Array:\n", full)

randome = np.random.random((2, 2))
print("Random Array:\n", randome)

seq = np.arange(10, 21, 2)
print("Sequence Array:", seq)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random Array:
 [[0.81229215 0.61292517]
 [0.55532036 0.97196536]]
Sequence Array: [10 12 14 16 18 20]
