## Numy array operations

In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print("basic slice:", arr[1:4])

print("slice with step:", arr[0:5:2])
print("slice with negative step:", arr[4:1:-1])


basic slice: [2 3 4]
slice with step: [1 3 5]
slice with negative step: [5 4 3]


In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("specific element:", arr_2d[1, 2])
print ("entire row:", arr_2d[0, :])
print("entire column:", arr_2d[:, 1])


specific element: 6
entire row: [1 2 3]
entire column: [2 5 8]


### sorting

In [6]:
unsorted_arr = np.array([3, 1, 4, 2, 5])
print("sorted array:", np.sort(unsorted_arr))

arr_2d_unsorted = np.array([[3, 1, 2], [6, 4, 5]])
print("sorted 2d array by columns:\n", np.sort(arr_2d_unsorted, axis=0) )


sorted array: [1 2 3 4 5]
sorted 2d array by columns:
 [[3 1 2]
 [6 4 5]]


### filter

In [10]:
num = np.array([10, 20, 30, 40, 50])
even_num = num[num % 20 == 0]
print("Filtered even numbers:", even_num)

Filtered even numbers: [20 40]


### filter with mask

In [11]:
mask = num > 25
print("Numbers greater than 25:", num[mask]) 

Numbers greater than 25: [30 40 50]


### fancy indexing vs np.where()

In [14]:
indices =  [0, 2, 4]
print("Elements at indices 0, 2, 4:", num[indices])

where_indices = np.where(num > 25)
print("Indices of elements greater than 25:", num[where_indices])


Elements at indices 0, 2, 4: [10 30 50]
Indices of elements greater than 25: [30 40 50]


In [17]:
condition_array = np.where(num > 25, num*2,num)
print("Conditionally modified array:", condition_array)

condition_array2 = np.where(num > 25, "true","false")
print("conditional array with true or false",condition_array2)


Conditionally modified array: [ 10  20  60  80 100]
conditional array with true or false ['false' 'false' 'true' 'true' 'true']


### adding and removing data

In [21]:
array = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

combined_array = np.concatenate((array, array2))
print("combined array:", combined_array)

combined array: [ 1  2  3  4  5 10 20 30 40 50]


### array compatibility

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c= np.array([7, 8, 9])

print("compatibilty shapes",a.shape == b.shape)

compatibilty shapes True


In [31]:
original =np.array([[1, 2, 3], [4, 5, 6]])
new_row = np.array([[7, 8, 9]])

appended_array = np.vstack((original, new_row))
print("Appended array:\n", appended_array)

new_column = np.array([[10], [11], [12]])
appended_array_col = np.hstack((appended_array, new_column))
print("Appended array with new column:\n", appended_array_col)


Appended array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Appended array with new column:
 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [32]:
array = np.array([1, 2, 3, 4, 5])
deleted_element_array = np.delete(array, 2)
print("Array after deleting element at index 2:", deleted_element_array)

Array after deleting element at index 2: [1 2 4 5]
